components:
  schemas:
    AggregateRating:
      description: https://www.schema.org/AggregateRating
      properties:
        bestRating:
          type: number
        id:
          format: int64
          type: integer
        ratingCount:
          type: number
        ratingValue:
          type: number
        worstRating:
          type: number
      type: object
    Comment:
      description: https://www.schema.org/Comment
      properties:
        comments:
          items:
            $ref: "#/components/schemas/Comment"
          type: array
        creator:
          $ref: "#/components/schemas/Creator"
        id:
          format: int64
          type: integer
        text:
          type: string
      type: object
    ContentDocument:
      description: https://www.schema.org/ContentDocument
      properties:
        contentUrl:
          format: uri
          type: string
        creator:
          $ref: "#/components/schemas/Creator"
        dateCreated:
          format: date-time
          type: string
        dateModified:
          format: date-time
          type: string
        encodingFormat:
          type: string
        fileExtension:
          type: string
        id:
          format: int64
          type: integer
        sizeInBytes:
          type: number
        title:
          type: string
      type: object
    ContentStructure:
      description: https://www.schema.org/ContentStructure
      properties:
        availableLanguages:
          items:
            type: string
          type: array
        contentSpace:
          format: int64
          type: integer
        creator:
          $ref: "#/components/schemas/Creator"
        dateCreated:
          format: date-time
          type: string
        dateModified:
          format: date-time
          type: string
        description:
          type: string
        fields:
          items:
            properties:
              dataType:
                type: string
              label:
                type: string
              localizable:
                type: boolean
              multiple:
                type: boolean
              inputControl:
                type: string
              predefinedValue:
                type: string
              name:
                type: string
              repeatable:
                type: boolean
              required:
                type: boolean
              showLabel:
                type: boolean
              options:
                items:
                  type: object
                  properties:
                    label:
                      type: string
                    value:
                      type: string
                type: array
            type: object
          type: array
        id:
          format: int64
          type: integer
        name:
          type: string
      type: object
    Creator:
      description: https://www.schema.org/Creator
      properties:
        additionalName:
          type: string
        familyName:
          type: string
        givenName:
          type: string
        id:
          format: int64
          type: integer
        image:
          format: uri
          type: string
        name:
          type: string
        profileURL:
          format: uri
          type: string
      type: object
    StructuredContent:
      description: https://www.schema.org/StructuredContent
      properties:
        aggregateRating:
          $ref: "#/components/schemas/AggregateRating"
        availableLanguages:
          items:
            type: string
          type: array
        category:
          items:
            format: int64
            type: integer
          type: array
        comment:
          items:
            $ref: "#/components/schemas/Comment"
          type: array
        contentSpace:
          format: int64
          type: integer
        contentStructure:
          allOf:
            - $ref: "#/components/schemas/ContentStructure"
          readOnly: true
        contentStructureId:
          format: int64
          type: integer
          writeOnly: true
        creator:
          $ref: "#/components/schemas/Creator"
        dateCreated:
          format: date-time
          type: string
        dateModified:
          format: date-time
          type: string
        datePublished:
          format: date-time
          type: string
        description:
          type: string
        id:
          format: int64
          type: integer
        keywords:
          items:
            type: string
          type: array
        lastReviewed:
          format: date-time
          type: string
        renderedContentsByTemplate:
          description: https://www.schema.org/templates
          items:
            properties:
              id:
                format: int64
                type: integer
              renderedContent:
                type: string
              template:
                type: string
            type: object
          type: array
        title:
          type: string
        values:
          description: https://www.schema.org/ContentFieldValue
          items:
            properties:
              dataType:
                type: string
              filterAndSortIdentifier:
                type: string
              id:
                format: int64
                type: integer
              inputControl:
                type: string
              label:
                type: string
              name:
                type: string
              value:
                anyOf:
                  - properties:
                      data:
                        type: string
                  - properties:
                      document:
                        allOf:
                          - $ref: "#/components/schemas/ContentDocument"
                      documentId:
                        format: int64
                        type: integer
                        writeOnly: true
                  - properties:
                      geo:
                        description: https://www.schema.org/GeoCoordinates
                        properties:
                          id:
                            format: int64
                            type: integer
                          latitude:
                            type: number
                          longitude:
                            type: number
                        type: object
                  - properties:
                      link:
                        format: uri
                        type: string
                  - properties:
                      structuredContent:
                        allOf:
                          - $ref: "#/components/schemas/StructuredContent"
                        readOnly: true
                      structuredContentId:
                        format: int64
                        type: integer
                        writeOnly: true
            type: object
          type: array
info:
  description: ""
  title: ""
  version: v1.0
openapi: 3.0.1
paths:
  "/aggregate-ratings/{aggregate-rating-id}":
    get:
      parameters:
        - in: path
          name: aggregate-rating-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AggregateRating"
          description: ""
      tags: ["AggregateRating"]
  "/comments/{comment-id}":
    get:
      parameters:
        - in: path
          name: comment-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Comment"
          description: ""
      tags: ["Comment"]
  "/comments/{comment-id}/comments":
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: per_page
          schema:
            type: integer
        - in: path
          name: comment-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Comment"
                type: array
          description: ""
      tags: ["Comment"]
  "/content-documents/{content-document-id}":
    delete:
      parameters:
        - in: path
          name: content-document-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        204:
          content:
            application/json: {}
          description: ""
      tags: ["ContentDocument"]
    get:
      parameters:
        - in: path
          name: content-document-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ContentDocument"
          description: ""
      tags: ["ContentDocument"]
  "/content-spaces/{content-space-id}/content-structures":
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: per_page
          schema:
            type: integer
        - in: path
          name: content-space-id
          required: true
          schema:
            format: int64
            type: integer
        - in: query
          name: filter
          schema:
            type: string
        - in: query
          name: sort
          schema:
            type: string
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/ContentStructure"
                type: array
          description: ""
      tags: ["ContentStructure"]
  "/content-spaces/{content-space-id}/content-structures/{content-structure-id}/structured-contents":
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: per_page
          schema:
            type: integer
        - in: path
          name: content-space-id
          required: true
          schema:
            format: int64
            type: integer
        - in: path
          name: content-structure-id
          required: true
          schema:
            format: int64
            type: integer
        - in: header
          name: Accept-Language
          schema:
            type: string
        - in: query
          name: filter
          schema:
            type: string
        - in: query
          name: sort
          schema:
            type: string
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/StructuredContent"
                type: array
          description: ""
      tags: ["StructuredContent"]
  "/content-spaces/{content-space-id}/structured-contents":
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: per_page
          schema:
            type: integer
        - in: path
          name: content-space-id
          required: true
          schema:
            format: int64
            type: integer
        - in: header
          name: Accept-Language
          schema:
            type: string
        - in: query
          name: filter
          schema:
            type: string
        - in: query
          name: sort
          schema:
            type: string
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/StructuredContent"
                type: array
          description: ""
      tags: ["StructuredContent"]
    patch:
      parameters:
        - in: path
          name: content-space-id
          required: true
          schema:
            format: int64
            type: integer
        - in: header
          name: Accept-Language
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StructuredContent"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StructuredContent"
          description: ""
      tags: ["StructuredContent"]
    post:
      parameters:
        - in: path
          name: content-space-id
          required: true
          schema:
            format: int64
            type: integer
        - in: header
          name: Accept-Language
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StructuredContent"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StructuredContent"
          description: ""
      tags: ["StructuredContent"]
  "/content-spaces/{content-space-id}/structured-contents/batch-create":
    post:
      parameters:
        - in: path
          name: content-space-id
          required: true
          schema:
            format: int64
            type: integer
        - in: header
          name: Accept-Language
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StructuredContent"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StructuredContent"
          description: ""
      tags: ["StructuredContent"]
  "/content-structures/{content-structure-id}":
    get:
      parameters:
        - in: path
          name: content-structure-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ContentStructure"
          description: ""
      tags: ["StructuredContent"]
  "/structured-contents/{structured-content-id}":
    delete:
      parameters:
        - in: path
          name: structured-content-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        204:
          content:
            application/json: {}
          description: ""
      tags: ["StructuredContent"]
    get:
      parameters:
        - in: path
          name: structured-content-id
          required: true
          schema:
            format: int64
            type: integer
        - in: header
          name: Accept-Language
          schema:
            type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StructuredContent"
          description: ""
      tags: ["StructuredContent"]
    put:
      parameters:
        - in: path
          name: structured-content-id
          required: true
          schema:
            format: int64
            type: integer
        - in: header
          name: Accept-Language
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StructuredContent"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StructuredContent"
          description: ""
      tags: ["StructuredContent"]
  "/structured-contents/{structured-content-id}/categories":
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: per_page
          schema:
            type: integer
        - in: path
          name: structured-content-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  format: int64
                  type: integer
                type: array
          description: ""
      tags: ["StructuredContent"]
    post:
      parameters:
        - in: path
          name: structured-content-id
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              format: int64
              type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                format: int64
                type: integer
          description: ""
      tags: ["StructuredContent"]
  "/structured-contents/{structured-content-id}/categories/batch-create":
    post:
      parameters:
        - in: path
          name: structured-content-id
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              format: int64
              type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                format: int64
                type: integer
          description: ""
      tags: ["StructuredContent"]
  "/structured-contents/{structured-content-id}/comments":
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: per_page
          schema:
            type: integer
        - in: path
          name: structured-content-id
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Comment"
                type: array
          description: ""
      tags: ["Comment"]